/gps/energy 1.332 MeV
/gps/particle gamma

/gps/pos/type Point
/gps/position 0. 0. 0. mm
/gps/ang/type iso

#/gps/direction 0. 0. 1.

#/gps/pos/type Volume
#/gps/pos/shape Cylinder
#/gps/pos/centre 2. 2. 2. cm
#/gps/pos/radius 2.5 cm
#/gps/pos/halfz 4. cm
#/gps/ang/type iso
#/gps/ene/type Pow
#/gps/ene/min 0.1 MeV
#/gps/ene/max 5. MeV
#/gps/alpha -2.

#/run/beamOn 10

#/run_msg/setfilename test_e400M
/run/beamOn 1000001
